//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AllocationNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllocationNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="UserAllocation" type="{urn:aseXML:r38}QuantityNotification"/>
 *         &lt;element name="ShipperChange" type="{urn:aseXML:r38}ShipperChangeRequestType"/>
 *         &lt;element name="ShipperReportRequest" type="{urn:aseXML:r38}ShipperChangeRequestType"/>
 *         &lt;element name="ShipperReportResponse" type="{urn:aseXML:r38}ShipperChangeRequestType"/>
 *         &lt;element name="PipelineNomination" type="{urn:aseXML:r38}QuantityNotification"/>
 *         &lt;element name="SubnetProfile" type="{urn:aseXML:r38}QuantityNotification"/>
 *         &lt;element name="PipelineProfile" type="{urn:aseXML:r38}QuantityNotification"/>
 *         &lt;element name="PipelineRatio" type="{urn:aseXML:r38}QuantityNotification"/>
 *         &lt;element name="AnticipatedWithdrawal" type="{urn:aseXML:r38}QuantityNotification"/>
 *         &lt;element name="IntervalMeterProfile" type="{urn:aseXML:r38}QuantityNotification"/>
 *         &lt;element name="SubnetProfileForecast" type="{urn:aseXML:r38}QuantityNotification"/>
 *         &lt;element name="UserProfileForecast" type="{urn:aseXML:r38}QuantityNotification"/>
 *         &lt;element name="GatePointInflow" type="{urn:aseXML:r38}QuantityNotification"/>
 *         &lt;element name="GatePointProfile" type="{urn:aseXML:r38}QuantityNotification"/>
 *         &lt;element name="EstimatedConsumption" type="{urn:aseXML:r38}QuantityNotification"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" type="{urn:aseXML:r38}r31" default="r31" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllocationNotification", propOrder = {
    "userAllocation",
    "shipperChange",
    "shipperReportRequest",
    "shipperReportResponse",
    "pipelineNomination",
    "subnetProfile",
    "pipelineProfile",
    "pipelineRatio",
    "anticipatedWithdrawal",
    "intervalMeterProfile",
    "subnetProfileForecast",
    "userProfileForecast",
    "gatePointInflow",
    "gatePointProfile",
    "estimatedConsumption"
})
public class AllocationNotification {

    @XmlElement(name = "UserAllocation")
    protected QuantityNotification userAllocation;
    @XmlElement(name = "ShipperChange")
    protected ShipperChangeRequestType shipperChange;
    @XmlElement(name = "ShipperReportRequest")
    protected ShipperChangeRequestType shipperReportRequest;
    @XmlElement(name = "ShipperReportResponse")
    protected ShipperChangeRequestType shipperReportResponse;
    @XmlElement(name = "PipelineNomination")
    protected QuantityNotification pipelineNomination;
    @XmlElement(name = "SubnetProfile")
    protected QuantityNotification subnetProfile;
    @XmlElement(name = "PipelineProfile")
    protected QuantityNotification pipelineProfile;
    @XmlElement(name = "PipelineRatio")
    protected QuantityNotification pipelineRatio;
    @XmlElement(name = "AnticipatedWithdrawal")
    protected QuantityNotification anticipatedWithdrawal;
    @XmlElement(name = "IntervalMeterProfile")
    protected QuantityNotification intervalMeterProfile;
    @XmlElement(name = "SubnetProfileForecast")
    protected QuantityNotification subnetProfileForecast;
    @XmlElement(name = "UserProfileForecast")
    protected QuantityNotification userProfileForecast;
    @XmlElement(name = "GatePointInflow")
    protected QuantityNotification gatePointInflow;
    @XmlElement(name = "GatePointProfile")
    protected QuantityNotification gatePointProfile;
    @XmlElement(name = "EstimatedConsumption")
    protected QuantityNotification estimatedConsumption;
    @XmlAttribute(name = "version")
    protected R31 version;

    /**
     * Gets the value of the userAllocation property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getUserAllocation() {
        return userAllocation;
    }

    /**
     * Sets the value of the userAllocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setUserAllocation(QuantityNotification value) {
        this.userAllocation = value;
    }

    /**
     * Gets the value of the shipperChange property.
     * 
     * @return
     *     possible object is
     *     {@link ShipperChangeRequestType }
     *     
     */
    public ShipperChangeRequestType getShipperChange() {
        return shipperChange;
    }

    /**
     * Sets the value of the shipperChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipperChangeRequestType }
     *     
     */
    public void setShipperChange(ShipperChangeRequestType value) {
        this.shipperChange = value;
    }

    /**
     * Gets the value of the shipperReportRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ShipperChangeRequestType }
     *     
     */
    public ShipperChangeRequestType getShipperReportRequest() {
        return shipperReportRequest;
    }

    /**
     * Sets the value of the shipperReportRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipperChangeRequestType }
     *     
     */
    public void setShipperReportRequest(ShipperChangeRequestType value) {
        this.shipperReportRequest = value;
    }

    /**
     * Gets the value of the shipperReportResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ShipperChangeRequestType }
     *     
     */
    public ShipperChangeRequestType getShipperReportResponse() {
        return shipperReportResponse;
    }

    /**
     * Sets the value of the shipperReportResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipperChangeRequestType }
     *     
     */
    public void setShipperReportResponse(ShipperChangeRequestType value) {
        this.shipperReportResponse = value;
    }

    /**
     * Gets the value of the pipelineNomination property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getPipelineNomination() {
        return pipelineNomination;
    }

    /**
     * Sets the value of the pipelineNomination property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setPipelineNomination(QuantityNotification value) {
        this.pipelineNomination = value;
    }

    /**
     * Gets the value of the subnetProfile property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getSubnetProfile() {
        return subnetProfile;
    }

    /**
     * Sets the value of the subnetProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setSubnetProfile(QuantityNotification value) {
        this.subnetProfile = value;
    }

    /**
     * Gets the value of the pipelineProfile property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getPipelineProfile() {
        return pipelineProfile;
    }

    /**
     * Sets the value of the pipelineProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setPipelineProfile(QuantityNotification value) {
        this.pipelineProfile = value;
    }

    /**
     * Gets the value of the pipelineRatio property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getPipelineRatio() {
        return pipelineRatio;
    }

    /**
     * Sets the value of the pipelineRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setPipelineRatio(QuantityNotification value) {
        this.pipelineRatio = value;
    }

    /**
     * Gets the value of the anticipatedWithdrawal property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getAnticipatedWithdrawal() {
        return anticipatedWithdrawal;
    }

    /**
     * Sets the value of the anticipatedWithdrawal property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setAnticipatedWithdrawal(QuantityNotification value) {
        this.anticipatedWithdrawal = value;
    }

    /**
     * Gets the value of the intervalMeterProfile property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getIntervalMeterProfile() {
        return intervalMeterProfile;
    }

    /**
     * Sets the value of the intervalMeterProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setIntervalMeterProfile(QuantityNotification value) {
        this.intervalMeterProfile = value;
    }

    /**
     * Gets the value of the subnetProfileForecast property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getSubnetProfileForecast() {
        return subnetProfileForecast;
    }

    /**
     * Sets the value of the subnetProfileForecast property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setSubnetProfileForecast(QuantityNotification value) {
        this.subnetProfileForecast = value;
    }

    /**
     * Gets the value of the userProfileForecast property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getUserProfileForecast() {
        return userProfileForecast;
    }

    /**
     * Sets the value of the userProfileForecast property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setUserProfileForecast(QuantityNotification value) {
        this.userProfileForecast = value;
    }

    /**
     * Gets the value of the gatePointInflow property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getGatePointInflow() {
        return gatePointInflow;
    }

    /**
     * Sets the value of the gatePointInflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setGatePointInflow(QuantityNotification value) {
        this.gatePointInflow = value;
    }

    /**
     * Gets the value of the gatePointProfile property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getGatePointProfile() {
        return gatePointProfile;
    }

    /**
     * Sets the value of the gatePointProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setGatePointProfile(QuantityNotification value) {
        this.gatePointProfile = value;
    }

    /**
     * Gets the value of the estimatedConsumption property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityNotification }
     *     
     */
    public QuantityNotification getEstimatedConsumption() {
        return estimatedConsumption;
    }

    /**
     * Sets the value of the estimatedConsumption property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityNotification }
     *     
     */
    public void setEstimatedConsumption(QuantityNotification value) {
        this.estimatedConsumption = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R31 }
     *     
     */
    public R31 getVersion() {
        if (version == null) {
            return R31 .R_31;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R31 }
     *     
     */
    public void setVersion(R31 value) {
        this.version = value;
    }

}
