//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AustralianFloorOrLevelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AustralianFloorOrLevelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="2"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="FL"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="L"/>
 *     &lt;enumeration value="LB"/>
 *     &lt;enumeration value="LG"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="OD"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="UG"/>
 *     &lt;enumeration value="RT"/>
 *     &lt;enumeration value="SB"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AustralianFloorOrLevelType")
@XmlEnum
public enum AustralianFloorOrLevelType {

    B,
    FL,
    G,
    L,
    LB,
    LG,
    M,
    OD,
    P,
    UG,
    RT,
    SB;

    public String value() {
        return name();
    }

    public static AustralianFloorOrLevelType fromValue(String v) {
        return valueOf(v);
    }

}
