//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Purpose - Define an Australian address
 * Detail - The Australian address format allows for either a structured or an unstructured physical address, with locality, state and postcode always being carried as structured elements. In addition, it supports postal address formats. It follows the definitions and rules set out in AS4590 for address exchange. 
 * 
 * It is important to note the occurrence frequency of elements within the format, particularly BuildingOrPropertyName, House and Street.
 * 	
 * 
 * <p>Java class for AustralianAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AustralianAddress">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="StructuredAddress" type="{urn:aseXML:r38}AustralianStructuredAddressComponents"/>
 *           &lt;element name="UnstructuredAddress">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="AddressLine" type="{urn:aseXML:r38}AustralianAddressLine" maxOccurs="3"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="SuburbOrPlaceOrLocality" type="{urn:aseXML:r38}AustralianSuburbOrPlaceOrLocality" minOccurs="0"/>
 *         &lt;element name="StateOrTerritory" type="{urn:aseXML:r38}AustralianStateOrTerritory"/>
 *         &lt;element name="PostCode" type="{urn:aseXML:r38}AustralianPostCode"/>
 *         &lt;element name="DeliveryPointIdentifier" type="{urn:aseXML:r38}AustralianDeliveryPointIdentifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AustralianAddress", propOrder = {
    "structuredAddress",
    "unstructuredAddress",
    "suburbOrPlaceOrLocality",
    "stateOrTerritory",
    "postCode",
    "deliveryPointIdentifier"
})
@XmlSeeAlso({
    FaultLocation.class
})
public class AustralianAddress {

    @XmlElement(name = "StructuredAddress")
    protected AustralianStructuredAddressComponents structuredAddress;
    @XmlElement(name = "UnstructuredAddress")
    protected AustralianAddress.UnstructuredAddress unstructuredAddress;
    @XmlElementRef(name = "SuburbOrPlaceOrLocality", type = JAXBElement.class, required = false)
    protected JAXBElement<String> suburbOrPlaceOrLocality;
    @XmlElement(name = "StateOrTerritory", required = true)
    @XmlSchemaType(name = "string")
    protected AustralianStateOrTerritory stateOrTerritory;
    @XmlElement(name = "PostCode", required = true)
    protected String postCode;
    @XmlElementRef(name = "DeliveryPointIdentifier", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> deliveryPointIdentifier;

    /**
     * Gets the value of the structuredAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AustralianStructuredAddressComponents }
     *     
     */
    public AustralianStructuredAddressComponents getStructuredAddress() {
        return structuredAddress;
    }

    /**
     * Sets the value of the structuredAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AustralianStructuredAddressComponents }
     *     
     */
    public void setStructuredAddress(AustralianStructuredAddressComponents value) {
        this.structuredAddress = value;
    }

    /**
     * Gets the value of the unstructuredAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AustralianAddress.UnstructuredAddress }
     *     
     */
    public AustralianAddress.UnstructuredAddress getUnstructuredAddress() {
        return unstructuredAddress;
    }

    /**
     * Sets the value of the unstructuredAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AustralianAddress.UnstructuredAddress }
     *     
     */
    public void setUnstructuredAddress(AustralianAddress.UnstructuredAddress value) {
        this.unstructuredAddress = value;
    }

    /**
     * Gets the value of the suburbOrPlaceOrLocality property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSuburbOrPlaceOrLocality() {
        return suburbOrPlaceOrLocality;
    }

    /**
     * Sets the value of the suburbOrPlaceOrLocality property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSuburbOrPlaceOrLocality(JAXBElement<String> value) {
        this.suburbOrPlaceOrLocality = value;
    }

    /**
     * Gets the value of the stateOrTerritory property.
     * 
     * @return
     *     possible object is
     *     {@link AustralianStateOrTerritory }
     *     
     */
    public AustralianStateOrTerritory getStateOrTerritory() {
        return stateOrTerritory;
    }

    /**
     * Sets the value of the stateOrTerritory property.
     * 
     * @param value
     *     allowed object is
     *     {@link AustralianStateOrTerritory }
     *     
     */
    public void setStateOrTerritory(AustralianStateOrTerritory value) {
        this.stateOrTerritory = value;
    }

    /**
     * Gets the value of the postCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostCode(String value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the deliveryPointIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getDeliveryPointIdentifier() {
        return deliveryPointIdentifier;
    }

    /**
     * Sets the value of the deliveryPointIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setDeliveryPointIdentifier(JAXBElement<Integer> value) {
        this.deliveryPointIdentifier = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AddressLine" type="{urn:aseXML:r38}AustralianAddressLine" maxOccurs="3"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "addressLine"
    })
    public static class UnstructuredAddress {

        @XmlElement(name = "AddressLine", required = true, nillable = true)
        protected List<String> addressLine;

        /**
         * Gets the value of the addressLine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the addressLine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAddressLine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAddressLine() {
            if (addressLine == null) {
                addressLine = new ArrayList<String>();
            }
            return this.addressLine;
        }

    }

}
