//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BidAllocationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BidAllocationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Fixed"/>
 *     &lt;enumeration value="Percentage of Surplus"/>
 *     &lt;enumeration value="Fixed of Surplus"/>
 *     &lt;enumeration value="Percentage of UETW"/>
 *     &lt;enumeration value="Fixed of UETW"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BidAllocationType")
@XmlEnum
public enum BidAllocationType {

    @XmlEnumValue("Fixed")
    FIXED("Fixed"),
    @XmlEnumValue("Percentage of Surplus")
    PERCENTAGE_OF_SURPLUS("Percentage of Surplus"),
    @XmlEnumValue("Fixed of Surplus")
    FIXED_OF_SURPLUS("Fixed of Surplus"),
    @XmlEnumValue("Percentage of UETW")
    PERCENTAGE_OF_UETW("Percentage of UETW"),
    @XmlEnumValue("Fixed of UETW")
    FIXED_OF_UETW("Fixed of UETW");
    private final String value;

    BidAllocationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BidAllocationType fromValue(String v) {
        for (BidAllocationType c: BidAllocationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
