//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * Purpose - Parameter definition for  SDR Traffic Light Report
 * Report Name - SDR Export
 * MSATS Report - STND_DAT_TRAFFICLGHT
 * 			
 * 
 * <p>Java class for CATSSDRTrafficLightReportParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CATSSDRTrafficLightReportParameters">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:aseXML:r38}BaseReportParameters">
 *       &lt;sequence>
 *         &lt;element name="StatsDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{urn:aseXML:r38}r19" default="r19" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CATSSDRTrafficLightReportParameters", propOrder = {
    "statsDate"
})
public class CATSSDRTrafficLightReportParameters
    extends BaseReportParameters
{

    @XmlElement(name = "StatsDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar statsDate;
    @XmlAttribute(name = "version")
    protected R19 version;

    /**
     * Gets the value of the statsDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStatsDate() {
        return statsDate;
    }

    /**
     * Sets the value of the statsDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStatsDate(XMLGregorianCalendar value) {
        this.statsDate = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R19 }
     *     
     */
    public R19 getVersion() {
        if (version == null) {
            return R19 .R_19;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R19 }
     *     
     */
    public void setVersion(R19 value) {
        this.version = value;
    }

}
