//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Purpose - Data provided on a notification with respect to a change request
 * 			
 * 
 * <p>Java class for CATSChangeRequestNotificationData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CATSChangeRequestNotificationData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Participant" type="{urn:aseXML:r38}PartyIdentifier"/>
 *         &lt;element name="RequestID" type="{urn:aseXML:r38}CATSRequestIdentifier"/>
 *         &lt;element name="ChangeStatusCode" type="{urn:aseXML:r38}CATSChangeStatusCode"/>
 *         &lt;element name="ChangeData" type="{urn:aseXML:r38}CATSChangeRequestData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CATSChangeRequestNotificationData", propOrder = {
    "participant",
    "requestID",
    "changeStatusCode",
    "changeData"
})
public class CATSChangeRequestNotificationData {

    @XmlElement(name = "Participant", required = true, nillable = true)
    protected PartyIdentifier participant;
    @XmlElement(name = "RequestID")
    @XmlSchemaType(name = "positiveInteger")
    protected long requestID;
    @XmlElement(name = "ChangeStatusCode", required = true)
    protected String changeStatusCode;
    @XmlElement(name = "ChangeData", required = true)
    protected CATSChangeRequestData changeData;

    /**
     * Gets the value of the participant property.
     * 
     * @return
     *     possible object is
     *     {@link PartyIdentifier }
     *     
     */
    public PartyIdentifier getParticipant() {
        return participant;
    }

    /**
     * Sets the value of the participant property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyIdentifier }
     *     
     */
    public void setParticipant(PartyIdentifier value) {
        this.participant = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     */
    public long getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     */
    public void setRequestID(long value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the changeStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeStatusCode() {
        return changeStatusCode;
    }

    /**
     * Sets the value of the changeStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeStatusCode(String value) {
        this.changeStatusCode = value;
    }

    /**
     * Gets the value of the changeData property.
     * 
     * @return
     *     possible object is
     *     {@link CATSChangeRequestData }
     *     
     */
    public CATSChangeRequestData getChangeData() {
        return changeData;
    }

    /**
     * Sets the value of the changeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CATSChangeRequestData }
     *     
     */
    public void setChangeData(CATSChangeRequestData value) {
        this.changeData = value;
    }

}
