//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ControlEquipmentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ControlEquipmentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="25"/>
 *     &lt;enumeration value="Internal Relay"/>
 *     &lt;enumeration value="External Relay"/>
 *     &lt;enumeration value="Internal Time Switch"/>
 *     &lt;enumeration value="External Time Switch"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ControlEquipmentType")
@XmlEnum
public enum ControlEquipmentType {

    @XmlEnumValue("Internal Relay")
    INTERNAL_RELAY("Internal Relay"),
    @XmlEnumValue("External Relay")
    EXTERNAL_RELAY("External Relay"),
    @XmlEnumValue("Internal Time Switch")
    INTERNAL_TIME_SWITCH("Internal Time Switch"),
    @XmlEnumValue("External Time Switch")
    EXTERNAL_TIME_SWITCH("External Time Switch");
    private final String value;

    ControlEquipmentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ControlEquipmentType fromValue(String v) {
        for (ControlEquipmentType c: ControlEquipmentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
