//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Application - Network Billing
 * 				TransactionExchange - 
 * 				TransactionGroup - NETB
 * 				Priority - Medium
 * 				Purpose - Submit dispute status change details to the Retailer
 * 				
 * 				NEM
 * 					B2B_NB_NSW_IP_v2.3_-_Effective_from_9Dec2002.doc
 * 					B2B_NB_SA_IP_v1-0_-_Effective_13Apr2003.doc
 * 					This complex type defines the transaction "..." - unknown in tech spec v1.3
 * 					This transaction is for use only in SA and NSW.
 * 			
 * 
 * <p>Java class for CreditNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="CreditData" type="{urn:aseXML:r38}CreditData"/>
 *         &lt;element name="CSVOutstandingInvoice" type="{urn:aseXML:r38}CSVRequestFormat"/>
 *         &lt;element name="CSVCreditBalance" type="{urn:aseXML:r38}CSVRequestFormat"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" type="{urn:aseXML:r38}r11" default="r11" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditNotification", propOrder = {
    "creditData",
    "csvOutstandingInvoice",
    "csvCreditBalance"
})
public class CreditNotification {

    @XmlElement(name = "CreditData")
    protected CreditData creditData;
    @XmlElement(name = "CSVOutstandingInvoice")
    protected CSVRequestFormat csvOutstandingInvoice;
    @XmlElement(name = "CSVCreditBalance")
    protected CSVRequestFormat csvCreditBalance;
    @XmlAttribute(name = "version")
    protected R11 version;

    /**
     * Gets the value of the creditData property.
     * 
     * @return
     *     possible object is
     *     {@link CreditData }
     *     
     */
    public CreditData getCreditData() {
        return creditData;
    }

    /**
     * Sets the value of the creditData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditData }
     *     
     */
    public void setCreditData(CreditData value) {
        this.creditData = value;
    }

    /**
     * Gets the value of the csvOutstandingInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link CSVRequestFormat }
     *     
     */
    public CSVRequestFormat getCSVOutstandingInvoice() {
        return csvOutstandingInvoice;
    }

    /**
     * Sets the value of the csvOutstandingInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSVRequestFormat }
     *     
     */
    public void setCSVOutstandingInvoice(CSVRequestFormat value) {
        this.csvOutstandingInvoice = value;
    }

    /**
     * Gets the value of the csvCreditBalance property.
     * 
     * @return
     *     possible object is
     *     {@link CSVRequestFormat }
     *     
     */
    public CSVRequestFormat getCSVCreditBalance() {
        return csvCreditBalance;
    }

    /**
     * Sets the value of the csvCreditBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSVRequestFormat }
     *     
     */
    public void setCSVCreditBalance(CSVRequestFormat value) {
        this.csvCreditBalance = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R11 }
     *     
     */
    public R11 getVersion() {
        if (version == null) {
            return R11 .R_11;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R11 }
     *     
     */
    public void setVersion(R11 value) {
        this.version = value;
    }

}
