//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Application - Network Billing
 * 				TransactionExchange - 
 * 				TransactionGroup - NETB
 * 				Priority - Medium
 * 				Purpose - Submit dispute items to the Distributor
 * 				NEM
 * 					B2B_NB_NSW_IP_v2.3_-_Effective_from_9Dec2002.doc
 * 					B2B_NB_SA_IP_v1-0_-_Effective_13Apr2003.doc
 * 					B2B_NB_Vic_IP_v1-1_-_Effective_13Jan2002.doc
 * 					This complex type defines the transaction "NBDISPUTES"
 * 					Optionally, disputed payment data may be provided for each line item for this transaction as per B2B_NB_NSW_IP_v2.3_-_Effective_from_9Dec2002.doc
 * 					This transaction is for use only in SA, NSW and VIC.
 * 			
 * 
 * <p>Java class for DisputeNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisputeNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="DisputeData" type="{urn:aseXML:r38}DisputeNotificationData"/>
 *         &lt;element name="CSVDispute" type="{urn:aseXML:r38}CSVRequestFormat"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" type="{urn:aseXML:r38}r11" default="r11" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisputeNotification", propOrder = {
    "disputeData",
    "csvDispute"
})
public class DisputeNotification {

    @XmlElement(name = "DisputeData")
    protected DisputeNotificationData disputeData;
    @XmlElement(name = "CSVDispute")
    protected CSVRequestFormat csvDispute;
    @XmlAttribute(name = "version")
    protected R11 version;

    /**
     * Gets the value of the disputeData property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeNotificationData }
     *     
     */
    public DisputeNotificationData getDisputeData() {
        return disputeData;
    }

    /**
     * Sets the value of the disputeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeNotificationData }
     *     
     */
    public void setDisputeData(DisputeNotificationData value) {
        this.disputeData = value;
    }

    /**
     * Gets the value of the csvDispute property.
     * 
     * @return
     *     possible object is
     *     {@link CSVRequestFormat }
     *     
     */
    public CSVRequestFormat getCSVDispute() {
        return csvDispute;
    }

    /**
     * Sets the value of the csvDispute property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSVRequestFormat }
     *     
     */
    public void setCSVDispute(CSVRequestFormat value) {
        this.csvDispute = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R11 }
     *     
     */
    public R11 getVersion() {
        if (version == null) {
            return R11 .R_11;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R11 }
     *     
     */
    public void setVersion(R11 value) {
        this.version = value;
    }

}
