//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Purpose - Row of the EmbeddedNetworkIdentifiers table
 * MSATS Data Model Table - CATS_Emb_Net_ID_Codes
 * Replication Table Name - EmbeddedNetworkIdentifiers
 * 			
 * 
 * <p>Java class for EmbeddedNetworkIdentifierRow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmbeddedNetworkIdentifierRow">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:aseXML:r38}ReplicationDateRangeRow">
 *       &lt;sequence>
 *         &lt;element name="Identifier" type="{urn:aseXML:r38}EmbeddedNetworkIdentifier"/>
 *         &lt;element name="Description" type="{urn:aseXML:r38}EmbeddedNetworkDescription"/>
 *         &lt;element name="Locality" type="{urn:aseXML:r38}AustralianSuburbOrPlaceOrLocality"/>
 *         &lt;element name="State" type="{urn:aseXML:r38}AustralianStateOrTerritory"/>
 *         &lt;element name="PostCode" type="{urn:aseXML:r38}AustralianPostCode"/>
 *         &lt;element name="ExemptEmbeddedNSP" type="{urn:aseXML:r38}PartyIdentifier" minOccurs="0"/>
 *         &lt;element name="DLFCodeParentNMI" type="{urn:aseXML:r38}DistributionLossFactorCode" minOccurs="0"/>
 *         &lt;element name="TNICodeParentNMI" type="{urn:aseXML:r38}TransmissionNodeIdentifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmbeddedNetworkIdentifierRow", propOrder = {
    "identifier",
    "description",
    "locality",
    "state",
    "postCode",
    "exemptEmbeddedNSP",
    "dlfCodeParentNMI",
    "tniCodeParentNMI"
})
public class EmbeddedNetworkIdentifierRow
    extends ReplicationDateRangeRow
{

    @XmlElement(name = "Identifier", required = true)
    protected String identifier;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Locality", required = true)
    protected String locality;
    @XmlElement(name = "State", required = true)
    @XmlSchemaType(name = "string")
    protected AustralianStateOrTerritory state;
    @XmlElement(name = "PostCode", required = true)
    protected String postCode;
    @XmlElementRef(name = "ExemptEmbeddedNSP", type = JAXBElement.class, required = false)
    protected JAXBElement<PartyIdentifier> exemptEmbeddedNSP;
    @XmlElementRef(name = "DLFCodeParentNMI", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dlfCodeParentNMI;
    @XmlElementRef(name = "TNICodeParentNMI", type = JAXBElement.class, required = false)
    protected JAXBElement<String> tniCodeParentNMI;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the locality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocality() {
        return locality;
    }

    /**
     * Sets the value of the locality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocality(String value) {
        this.locality = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link AustralianStateOrTerritory }
     *     
     */
    public AustralianStateOrTerritory getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link AustralianStateOrTerritory }
     *     
     */
    public void setState(AustralianStateOrTerritory value) {
        this.state = value;
    }

    /**
     * Gets the value of the postCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostCode(String value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the exemptEmbeddedNSP property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PartyIdentifier }{@code >}
     *     
     */
    public JAXBElement<PartyIdentifier> getExemptEmbeddedNSP() {
        return exemptEmbeddedNSP;
    }

    /**
     * Sets the value of the exemptEmbeddedNSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PartyIdentifier }{@code >}
     *     
     */
    public void setExemptEmbeddedNSP(JAXBElement<PartyIdentifier> value) {
        this.exemptEmbeddedNSP = value;
    }

    /**
     * Gets the value of the dlfCodeParentNMI property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDLFCodeParentNMI() {
        return dlfCodeParentNMI;
    }

    /**
     * Sets the value of the dlfCodeParentNMI property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDLFCodeParentNMI(JAXBElement<String> value) {
        this.dlfCodeParentNMI = value;
    }

    /**
     * Gets the value of the tniCodeParentNMI property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTNICodeParentNMI() {
        return tniCodeParentNMI;
    }

    /**
     * Sets the value of the tniCodeParentNMI property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTNICodeParentNMI(JAXBElement<String> value) {
        this.tniCodeParentNMI = value;
    }

}
