//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnumScopeOfWorkType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnumScopeOfWorkType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="25"/>
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="Line"/>
 *     &lt;enumeration value="Substn"/>
 *     &lt;enumeration value="Line/Substn"/>
 *     &lt;enumeration value="Live Line"/>
 *     &lt;enumeration value="Live Substn"/>
 *     &lt;enumeration value="Live Line/Substn"/>
 *     &lt;enumeration value="Protection"/>
 *     &lt;enumeration value="SCADA"/>
 *     &lt;enumeration value="Communications"/>
 *     &lt;enumeration value="Other secondary equipt"/>
 *     &lt;enumeration value="Auto Control Scheme"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EnumScopeOfWorkType")
@XmlEnum
public enum EnumScopeOfWorkType {

    @XmlEnumValue("Line")
    LINE("Line"),
    @XmlEnumValue("Substn")
    SUBSTN("Substn"),
    @XmlEnumValue("Line/Substn")
    LINE_SUBSTN("Line/Substn"),
    @XmlEnumValue("Live Line")
    LIVE_LINE("Live Line"),
    @XmlEnumValue("Live Substn")
    LIVE_SUBSTN("Live Substn"),
    @XmlEnumValue("Live Line/Substn")
    LIVE_LINE_SUBSTN("Live Line/Substn"),
    @XmlEnumValue("Protection")
    PROTECTION("Protection"),
    SCADA("SCADA"),
    @XmlEnumValue("Communications")
    COMMUNICATIONS("Communications"),
    @XmlEnumValue("Other secondary equipt")
    OTHER_SECONDARY_EQUIPT("Other secondary equipt"),
    @XmlEnumValue("Auto Control Scheme")
    AUTO_CONTROL_SCHEME("Auto Control Scheme"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    EnumScopeOfWorkType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumScopeOfWorkType fromValue(String v) {
        for (EnumScopeOfWorkType c: EnumScopeOfWorkType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
