//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnumOutageStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnumOutageStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="20"/>
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="SUBMIT"/>
 *     &lt;enumeration value="RESUBMIT"/>
 *     &lt;enumeration value="MTLTP"/>
 *     &lt;enumeration value="STLTP"/>
 *     &lt;enumeration value="PDLTP"/>
 *     &lt;enumeration value="PTP"/>
 *     &lt;enumeration value="PTR"/>
 *     &lt;enumeration value="COMPLETE"/>
 *     &lt;enumeration value="UTP"/>
 *     &lt;enumeration value="WD REQ"/>
 *     &lt;enumeration value="WDRAWN"/>
 *     &lt;enumeration value="INFO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EnumOutageStatusType")
@XmlEnum
public enum EnumOutageStatusType {

    SUBMIT("SUBMIT"),
    RESUBMIT("RESUBMIT"),
    MTLTP("MTLTP"),
    STLTP("STLTP"),
    PDLTP("PDLTP"),
    PTP("PTP"),
    PTR("PTR"),
    COMPLETE("COMPLETE"),
    UTP("UTP"),
    @XmlEnumValue("WD REQ")
    WD_REQ("WD REQ"),
    WDRAWN("WDRAWN"),
    INFO("INFO");
    private final String value;

    EnumOutageStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumOutageStatusType fromValue(String v) {
        for (EnumOutageStatusType c: EnumOutageStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
