//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Purpose - Definition for IAITExpiredImbalanceTradeRpt
 * Report Details - Notification of a Expired Trade.
 * 			
 * 
 * <p>Java class for ExpiredImbalanceTradeRpt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpiredImbalanceTradeRpt">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:aseXML:r38}BaseReportFormat">
 *       &lt;sequence>
 *         &lt;element name="ExpiredImbalanceData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="InitiatingReceiptID" type="{urn:aseXML:r38}ReceiptIdentifier"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpiredImbalanceTradeRpt", propOrder = {
    "expiredImbalanceData"
})
public class ExpiredImbalanceTradeRpt
    extends BaseReportFormat
{

    @XmlElement(name = "ExpiredImbalanceData", required = true)
    protected ExpiredImbalanceTradeRpt.ExpiredImbalanceData expiredImbalanceData;

    /**
     * Gets the value of the expiredImbalanceData property.
     * 
     * @return
     *     possible object is
     *     {@link ExpiredImbalanceTradeRpt.ExpiredImbalanceData }
     *     
     */
    public ExpiredImbalanceTradeRpt.ExpiredImbalanceData getExpiredImbalanceData() {
        return expiredImbalanceData;
    }

    /**
     * Sets the value of the expiredImbalanceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpiredImbalanceTradeRpt.ExpiredImbalanceData }
     *     
     */
    public void setExpiredImbalanceData(ExpiredImbalanceTradeRpt.ExpiredImbalanceData value) {
        this.expiredImbalanceData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="InitiatingReceiptID" type="{urn:aseXML:r38}ReceiptIdentifier"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "initiatingReceiptID"
    })
    public static class ExpiredImbalanceData {

        @XmlElement(name = "InitiatingReceiptID", required = true)
        protected String initiatingReceiptID;

        /**
         * Gets the value of the initiatingReceiptID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInitiatingReceiptID() {
            return initiatingReceiptID;
        }

        /**
         * Sets the value of the initiatingReceiptID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInitiatingReceiptID(String value) {
            this.initiatingReceiptID = value;
        }

    }

}
