//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Symptom/s of the fault
 * 
 * <p>Java class for FaultSymptoms complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FaultSymptoms">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Symptom" maxOccurs="4">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ACR tripped"/>
 *               &lt;enumeration value="Area street lights out"/>
 *               &lt;enumeration value="Car hit pole"/>
 *               &lt;enumeration value="Dim lights"/>
 *               &lt;enumeration value="Damage to u/ground pillar"/>
 *               &lt;enumeration value="Electric shock"/>
 *               &lt;enumeration value="Explosion reports"/>
 *               &lt;enumeration value="Fuse down"/>
 *               &lt;enumeration value="Fire"/>
 *               &lt;enumeration value="Glow reports"/>
 *               &lt;enumeration value="High voltage injection"/>
 *               &lt;enumeration value="Hot water 16h boost"/>
 *               &lt;enumeration value="Intermittent supply"/>
 *               &lt;enumeration value="Insufficient hot water"/>
 *               &lt;enumeration value="Light/s out found by patrol"/>
 *               &lt;enumeration value="Loss of supply - complete"/>
 *               &lt;enumeration value="Loss of supply - partial"/>
 *               &lt;enumeration value="Meter/timeswitch faulty"/>
 *               &lt;enumeration value="No hot water"/>
 *               &lt;enumeration value="Not listed"/>
 *               &lt;enumeration value="Other"/>
 *               &lt;enumeration value="Pole Down"/>
 *               &lt;enumeration value="Pole Fire"/>
 *               &lt;enumeration value="Urgent Public Hazard Report "/>
 *               &lt;enumeration value="Urgent Public Hazard Report - fire"/>
 *               &lt;enumeration value="Planned Outage"/>
 *               &lt;enumeration value="Street lights out"/>
 *               &lt;enumeration value="Sparks Reports"/>
 *               &lt;enumeration value="Tree Near Wire"/>
 *               &lt;enumeration value="Tree On Wire"/>
 *               &lt;enumeration value="TV Interference"/>
 *               &lt;enumeration value="Underground Cable"/>
 *               &lt;enumeration value="Unknown"/>
 *               &lt;enumeration value="Voltage complaints"/>
 *               &lt;enumeration value="Wires down - pole to house"/>
 *               &lt;enumeration value="Wires down - pole to pole"/>
 *               &lt;enumeration value="Watchman Light Out"/>
 *               &lt;enumeration value="Wildlife report"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FaultSymptoms", propOrder = {
    "symptom"
})
public class FaultSymptoms {

    @XmlElement(name = "Symptom", required = true)
    protected List<String> symptom;

    /**
     * Gets the value of the symptom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the symptom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSymptom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSymptom() {
        if (symptom == null) {
            symptom = new ArrayList<String>();
        }
        return this.symptom;
    }

}
