//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Purpose - Network invoice record type - "020" - InvoiceSummary
 * 
 * <p>Java class for InvoiceSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceSummary">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:aseXML:r38}BaseInvoice">
 *       &lt;sequence>
 *         &lt;element name="InvoiceDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DueDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Retailer" type="{urn:aseXML:r38}GSTDetails"/>
 *         &lt;element name="Distributor" type="{urn:aseXML:r38}GSTDetails"/>
 *         &lt;element name="GSTStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="150"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Amount" type="{urn:aseXML:r38}PaymentData"/>
 *         &lt;element name="FirstTransactionID" type="{urn:aseXML:r38}TransactionID" minOccurs="0"/>
 *         &lt;element name="LastTransactionID" type="{urn:aseXML:r38}TransactionID" minOccurs="0"/>
 *         &lt;element name="TotalNumberOfChargeItems" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TotalNumberOfDetailRecords" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceSummary", propOrder = {
    "invoiceDate",
    "dueDate",
    "retailer",
    "distributor",
    "gstStatus",
    "amount",
    "firstTransactionID",
    "lastTransactionID",
    "totalNumberOfChargeItems",
    "totalNumberOfDetailRecords"
})
public class InvoiceSummary
    extends BaseInvoice
{

    @XmlElement(name = "InvoiceDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar invoiceDate;
    @XmlElement(name = "DueDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDate;
    @XmlElement(name = "Retailer", required = true)
    protected GSTDetails retailer;
    @XmlElement(name = "Distributor", required = true)
    protected GSTDetails distributor;
    @XmlElement(name = "GSTStatus", required = true)
    protected String gstStatus;
    @XmlElement(name = "Amount", required = true)
    protected PaymentData amount;
    @XmlElement(name = "FirstTransactionID")
    protected String firstTransactionID;
    @XmlElement(name = "LastTransactionID")
    protected String lastTransactionID;
    @XmlElement(name = "TotalNumberOfChargeItems")
    protected BigDecimal totalNumberOfChargeItems;
    @XmlElement(name = "TotalNumberOfDetailRecords")
    protected BigDecimal totalNumberOfDetailRecords;

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceDate(XMLGregorianCalendar value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the retailer property.
     * 
     * @return
     *     possible object is
     *     {@link GSTDetails }
     *     
     */
    public GSTDetails getRetailer() {
        return retailer;
    }

    /**
     * Sets the value of the retailer property.
     * 
     * @param value
     *     allowed object is
     *     {@link GSTDetails }
     *     
     */
    public void setRetailer(GSTDetails value) {
        this.retailer = value;
    }

    /**
     * Gets the value of the distributor property.
     * 
     * @return
     *     possible object is
     *     {@link GSTDetails }
     *     
     */
    public GSTDetails getDistributor() {
        return distributor;
    }

    /**
     * Sets the value of the distributor property.
     * 
     * @param value
     *     allowed object is
     *     {@link GSTDetails }
     *     
     */
    public void setDistributor(GSTDetails value) {
        this.distributor = value;
    }

    /**
     * Gets the value of the gstStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGSTStatus() {
        return gstStatus;
    }

    /**
     * Sets the value of the gstStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGSTStatus(String value) {
        this.gstStatus = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentData }
     *     
     */
    public PaymentData getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentData }
     *     
     */
    public void setAmount(PaymentData value) {
        this.amount = value;
    }

    /**
     * Gets the value of the firstTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstTransactionID() {
        return firstTransactionID;
    }

    /**
     * Sets the value of the firstTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstTransactionID(String value) {
        this.firstTransactionID = value;
    }

    /**
     * Gets the value of the lastTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTransactionID() {
        return lastTransactionID;
    }

    /**
     * Sets the value of the lastTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTransactionID(String value) {
        this.lastTransactionID = value;
    }

    /**
     * Gets the value of the totalNumberOfChargeItems property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalNumberOfChargeItems() {
        return totalNumberOfChargeItems;
    }

    /**
     * Sets the value of the totalNumberOfChargeItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalNumberOfChargeItems(BigDecimal value) {
        this.totalNumberOfChargeItems = value;
    }

    /**
     * Gets the value of the totalNumberOfDetailRecords property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalNumberOfDetailRecords() {
        return totalNumberOfDetailRecords;
    }

    /**
     * Sets the value of the totalNumberOfDetailRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalNumberOfDetailRecords(BigDecimal value) {
        this.totalNumberOfDetailRecords = value;
    }

}
