//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Purpose - defines the footer network billing invoice for NSW
 * 
 * <p>Java class for InvoiceNotificationFooter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceNotificationFooter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceRecordCount" type="{urn:aseXML:r38}RecordCount"/>
 *         &lt;element name="ChargeRecordCount" type="{urn:aseXML:r38}RecordCount"/>
 *         &lt;element name="Payment" type="{urn:aseXML:r38}PaymentData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceNotificationFooter", propOrder = {
    "invoiceRecordCount",
    "chargeRecordCount",
    "payment"
})
public class InvoiceNotificationFooter {

    @XmlElement(name = "InvoiceRecordCount", required = true)
    protected BigInteger invoiceRecordCount;
    @XmlElement(name = "ChargeRecordCount", required = true)
    protected BigInteger chargeRecordCount;
    @XmlElement(name = "Payment", required = true)
    protected PaymentData payment;

    /**
     * Gets the value of the invoiceRecordCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInvoiceRecordCount() {
        return invoiceRecordCount;
    }

    /**
     * Sets the value of the invoiceRecordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInvoiceRecordCount(BigInteger value) {
        this.invoiceRecordCount = value;
    }

    /**
     * Gets the value of the chargeRecordCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChargeRecordCount() {
        return chargeRecordCount;
    }

    /**
     * Sets the value of the chargeRecordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChargeRecordCount(BigInteger value) {
        this.chargeRecordCount = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentData }
     *     
     */
    public PaymentData getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentData }
     *     
     */
    public void setPayment(PaymentData value) {
        this.payment = value;
    }

}
