//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobEnquiryCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JobEnquiryCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AML"/>
 *     &lt;enumeration value="CSL"/>
 *     &lt;enumeration value="CLT"/>
 *     &lt;enumeration value="DFC"/>
 *     &lt;enumeration value="DSD"/>
 *     &lt;enumeration value="EBD"/>
 *     &lt;enumeration value="EBS"/>
 *     &lt;enumeration value="ECO"/>
 *     &lt;enumeration value="EFB"/>
 *     &lt;enumeration value="EMG"/>
 *     &lt;enumeration value="EMT"/>
 *     &lt;enumeration value="EOT"/>
 *     &lt;enumeration value="ESE"/>
 *     &lt;enumeration value="EST"/>
 *     &lt;enumeration value="EXP"/>
 *     &lt;enumeration value="FAP"/>
 *     &lt;enumeration value="FAT"/>
 *     &lt;enumeration value="FHS"/>
 *     &lt;enumeration value="FMN"/>
 *     &lt;enumeration value="FMT"/>
 *     &lt;enumeration value="FSV"/>
 *     &lt;enumeration value="MAP"/>
 *     &lt;enumeration value="MBO"/>
 *     &lt;enumeration value="MCH"/>
 *     &lt;enumeration value="MDM"/>
 *     &lt;enumeration value="MDO"/>
 *     &lt;enumeration value="MFX"/>
 *     &lt;enumeration value="MFXA"/>
 *     &lt;enumeration value="MHA"/>
 *     &lt;enumeration value="MRC"/>
 *     &lt;enumeration value="MRF"/>
 *     &lt;enumeration value="MRG"/>
 *     &lt;enumeration value="MRM"/>
 *     &lt;enumeration value="MRR"/>
 *     &lt;enumeration value="MRT"/>
 *     &lt;enumeration value="MST"/>
 *     &lt;enumeration value="MTE"/>
 *     &lt;enumeration value="MTJ"/>
 *     &lt;enumeration value="MTN"/>
 *     &lt;enumeration value="OTH"/>
 *     &lt;enumeration value="RML"/>
 *     &lt;enumeration value="RSD"/>
 *     &lt;enumeration value="RSR"/>
 *     &lt;enumeration value="SBS"/>
 *     &lt;enumeration value="SCR"/>
 *     &lt;enumeration value="SDR"/>
 *     &lt;enumeration value="SNG"/>
 *     &lt;enumeration value="SPN"/>
 *     &lt;enumeration value="UEF"/>
 *     &lt;enumeration value="UMS"/>
 *     &lt;enumeration value="USR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "JobEnquiryCode")
@XmlEnum
public enum JobEnquiryCode {

    AML,
    CSL,
    CLT,
    DFC,
    DSD,
    EBD,
    EBS,
    ECO,
    EFB,
    EMG,
    EMT,
    EOT,
    ESE,
    EST,
    EXP,
    FAP,
    FAT,
    FHS,
    FMN,
    FMT,
    FSV,
    MAP,
    MBO,
    MCH,
    MDM,
    MDO,
    MFX,
    MFXA,
    MHA,
    MRC,
    MRF,
    MRG,
    MRM,
    MRR,
    MRT,
    MST,
    MTE,
    MTJ,
    MTN,
    OTH,
    RML,
    RSD,
    RSR,
    SBS,
    SCR,
    SDR,
    SNG,
    SPN,
    UEF,
    UMS,
    USR;

    public String value() {
        return name();
    }

    public static JobEnquiryCode fromValue(String v) {
        return valueOf(v);
    }

}
