//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LifeSupportData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LifeSupportData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NMI" type="{urn:aseXML:r38}NMI"/>
 *         &lt;element name="SiteAddress" type="{urn:aseXML:r38}Address" minOccurs="0"/>
 *         &lt;element name="Reason" type="{urn:aseXML:r38}UpdateReason"/>
 *         &lt;element name="RegistrationOwner" type="{urn:aseXML:r38}YesNo" minOccurs="0"/>
 *         &lt;element name="Status" type="{urn:aseXML:r38}LifeSupportStatus"/>
 *         &lt;element name="DateRequired" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Equipment" type="{urn:aseXML:r38}LifeSupportEquipmentType" minOccurs="0"/>
 *         &lt;element name="ManagementContactDetail" type="{urn:aseXML:r38}CustomerDetail" minOccurs="0"/>
 *         &lt;element name="PreferredContactMethod" type="{urn:aseXML:r38}ContactMethod" minOccurs="0"/>
 *         &lt;element name="SpecialNotes" type="{urn:aseXML:r38}SpecialComments" minOccurs="0"/>
 *         &lt;element name="LastModifiedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LifeSupportData", propOrder = {
    "nmi",
    "siteAddress",
    "reason",
    "registrationOwner",
    "status",
    "dateRequired",
    "equipment",
    "managementContactDetail",
    "preferredContactMethod",
    "specialNotes",
    "lastModifiedDateTime"
})
public class LifeSupportData {

    @XmlElement(name = "NMI", required = true)
    protected NMI nmi;
    @XmlElement(name = "SiteAddress")
    protected Address siteAddress;
    @XmlElement(name = "Reason", required = true)
    @XmlSchemaType(name = "string")
    protected UpdateReason reason;
    @XmlElement(name = "RegistrationOwner")
    @XmlSchemaType(name = "string")
    protected YesNo registrationOwner;
    @XmlElement(name = "Status", required = true)
    @XmlSchemaType(name = "string")
    protected LifeSupportStatus status;
    @XmlElement(name = "DateRequired")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateRequired;
    @XmlElement(name = "Equipment")
    @XmlSchemaType(name = "string")
    protected LifeSupportEquipmentType equipment;
    @XmlElement(name = "ManagementContactDetail")
    protected CustomerDetail managementContactDetail;
    @XmlElement(name = "PreferredContactMethod")
    @XmlSchemaType(name = "string")
    protected ContactMethod preferredContactMethod;
    @XmlElement(name = "SpecialNotes")
    protected SpecialComments specialNotes;
    @XmlElement(name = "LastModifiedDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedDateTime;

    /**
     * Gets the value of the nmi property.
     * 
     * @return
     *     possible object is
     *     {@link NMI }
     *     
     */
    public NMI getNMI() {
        return nmi;
    }

    /**
     * Sets the value of the nmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link NMI }
     *     
     */
    public void setNMI(NMI value) {
        this.nmi = value;
    }

    /**
     * Gets the value of the siteAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getSiteAddress() {
        return siteAddress;
    }

    /**
     * Sets the value of the siteAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setSiteAddress(Address value) {
        this.siteAddress = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateReason }
     *     
     */
    public UpdateReason getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateReason }
     *     
     */
    public void setReason(UpdateReason value) {
        this.reason = value;
    }

    /**
     * Gets the value of the registrationOwner property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getRegistrationOwner() {
        return registrationOwner;
    }

    /**
     * Sets the value of the registrationOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setRegistrationOwner(YesNo value) {
        this.registrationOwner = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link LifeSupportStatus }
     *     
     */
    public LifeSupportStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeSupportStatus }
     *     
     */
    public void setStatus(LifeSupportStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the dateRequired property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateRequired() {
        return dateRequired;
    }

    /**
     * Sets the value of the dateRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateRequired(XMLGregorianCalendar value) {
        this.dateRequired = value;
    }

    /**
     * Gets the value of the equipment property.
     * 
     * @return
     *     possible object is
     *     {@link LifeSupportEquipmentType }
     *     
     */
    public LifeSupportEquipmentType getEquipment() {
        return equipment;
    }

    /**
     * Sets the value of the equipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeSupportEquipmentType }
     *     
     */
    public void setEquipment(LifeSupportEquipmentType value) {
        this.equipment = value;
    }

    /**
     * Gets the value of the managementContactDetail property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDetail }
     *     
     */
    public CustomerDetail getManagementContactDetail() {
        return managementContactDetail;
    }

    /**
     * Sets the value of the managementContactDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDetail }
     *     
     */
    public void setManagementContactDetail(CustomerDetail value) {
        this.managementContactDetail = value;
    }

    /**
     * Gets the value of the preferredContactMethod property.
     * 
     * @return
     *     possible object is
     *     {@link ContactMethod }
     *     
     */
    public ContactMethod getPreferredContactMethod() {
        return preferredContactMethod;
    }

    /**
     * Sets the value of the preferredContactMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactMethod }
     *     
     */
    public void setPreferredContactMethod(ContactMethod value) {
        this.preferredContactMethod = value;
    }

    /**
     * Gets the value of the specialNotes property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialComments }
     *     
     */
    public SpecialComments getSpecialNotes() {
        return specialNotes;
    }

    /**
     * Sets the value of the specialNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialComments }
     *     
     */
    public void setSpecialNotes(SpecialComments value) {
        this.specialNotes = value;
    }

    /**
     * Gets the value of the lastModifiedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedDateTime() {
        return lastModifiedDateTime;
    }

    /**
     * Sets the value of the lastModifiedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedDateTime(XMLGregorianCalendar value) {
        this.lastModifiedDateTime = value;
    }

}
