//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoadDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoadDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PerHour" type="{urn:aseXML:r38}LoadDetailsPerHour"/>
 *         &lt;element name="PerAnnum" type="{urn:aseXML:r38}LoadDetailsPerAnnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoadDetails", propOrder = {
    "perHour",
    "perAnnum"
})
public class LoadDetails {

    @XmlElement(name = "PerHour", required = true)
    protected BigInteger perHour;
    @XmlElement(name = "PerAnnum")
    protected BigInteger perAnnum;

    /**
     * Gets the value of the perHour property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPerHour() {
        return perHour;
    }

    /**
     * Sets the value of the perHour property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPerHour(BigInteger value) {
        this.perHour = value;
    }

    /**
     * Gets the value of the perAnnum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPerAnnum() {
        return perAnnum;
    }

    /**
     * Sets the value of the perAnnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPerAnnum(BigInteger value) {
        this.perAnnum = value;
    }

}
