//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MDMNMISelectionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MDMNMISelectionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SecondTierNMIs"/>
 *     &lt;enumeration value="AllNMIs"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MDMNMISelectionType")
@XmlEnum
public enum MDMNMISelectionType {

    @XmlEnumValue("SecondTierNMIs")
    SECOND_TIER_NM_IS("SecondTierNMIs"),
    @XmlEnumValue("AllNMIs")
    ALL_NM_IS("AllNMIs");
    private final String value;

    MDMNMISelectionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MDMNMISelectionType fromValue(String v) {
        for (MDMNMISelectionType c: MDMNMISelectionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
