//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Purpose - Row of the NMI Ranges table
 * MSATS Data Model Table - CATS_NMI_RANGES
 * Replication Table Name – NMIRanges
 * 		
 * 
 * <p>Java class for NMIRangesRow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NMIRangesRow">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:aseXML:r38}ReplicationBaseRow">
 *       &lt;sequence>
 *         &lt;element name="Participant" type="{urn:aseXML:r38}PartyIdentifier" minOccurs="0"/>
 *         &lt;element name="NMIBlockFrom" type="{urn:aseXML:r38}NMIBase" minOccurs="0"/>
 *         &lt;element name="NMIBlockTo" type="{urn:aseXML:r38}NMIBase" minOccurs="0"/>
 *         &lt;element name="NMIRangesAttribute" type="{urn:aseXML:r38}NMIRangesAttributeType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NMIRangesRow", propOrder = {
    "participant",
    "nmiBlockFrom",
    "nmiBlockTo",
    "nmiRangesAttribute"
})
public class NMIRangesRow
    extends ReplicationBaseRow
{

    @XmlElementRef(name = "Participant", type = JAXBElement.class, required = false)
    protected JAXBElement<PartyIdentifier> participant;
    @XmlElementRef(name = "NMIBlockFrom", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nmiBlockFrom;
    @XmlElementRef(name = "NMIBlockTo", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nmiBlockTo;
    @XmlElement(name = "NMIRangesAttribute", required = true)
    protected String nmiRangesAttribute;

    /**
     * Gets the value of the participant property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PartyIdentifier }{@code >}
     *     
     */
    public JAXBElement<PartyIdentifier> getParticipant() {
        return participant;
    }

    /**
     * Sets the value of the participant property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PartyIdentifier }{@code >}
     *     
     */
    public void setParticipant(JAXBElement<PartyIdentifier> value) {
        this.participant = value;
    }

    /**
     * Gets the value of the nmiBlockFrom property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNMIBlockFrom() {
        return nmiBlockFrom;
    }

    /**
     * Sets the value of the nmiBlockFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNMIBlockFrom(JAXBElement<String> value) {
        this.nmiBlockFrom = value;
    }

    /**
     * Gets the value of the nmiBlockTo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNMIBlockTo() {
        return nmiBlockTo;
    }

    /**
     * Sets the value of the nmiBlockTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNMIBlockTo(JAXBElement<String> value) {
        this.nmiBlockTo = value;
    }

    /**
     * Gets the value of the nmiRangesAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNMIRangesAttribute() {
        return nmiRangesAttribute;
    }

    /**
     * Sets the value of the nmiRangesAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNMIRangesAttribute(String value) {
        this.nmiRangesAttribute = value;
    }

}
