//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A NEMMCO assessment of one or more TNSP outages
 * 
 * <p>Java class for NOSAssessmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NOSAssessmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SheetId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AssessmentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="AssessmentTitle">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="128"/>
 *               &lt;whiteSpace value="preserve"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RequiresReview" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Outage" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CompanyBookingId" type="{urn:aseXML:r38}CompanyBookingIdType"/>
 *                   &lt;element name="CompanyOutageId" type="{urn:aseXML:r38}CompanyOutageIdType"/>
 *                   &lt;element name="TNSPId" type="{urn:aseXML:r38}PartyIdentifier" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="operationType" type="{urn:aseXML:r38}NOSOperationType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Constraint" type="{urn:aseXML:r38}NOSConstraintType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Issue" type="{urn:aseXML:r38}NOSIssueType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Note" type="{urn:aseXML:r38}NOSAssessmentNoteType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Limit" type="{urn:aseXML:r38}NOSRiemnsLimitType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operationType" type="{urn:aseXML:r38}NOSOperationType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NOSAssessmentType", propOrder = {
    "sheetId",
    "assessmentDate",
    "assessmentTitle",
    "requiresReview",
    "outage",
    "constraint",
    "issue",
    "note",
    "limit"
})
public class NOSAssessmentType {

    @XmlElement(name = "SheetId")
    protected int sheetId;
    @XmlElement(name = "AssessmentDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar assessmentDate;
    @XmlElement(name = "AssessmentTitle", required = true)
    protected String assessmentTitle;
    @XmlElement(name = "RequiresReview")
    protected boolean requiresReview;
    @XmlElement(name = "Outage")
    protected List<NOSAssessmentType.Outage> outage;
    @XmlElement(name = "Constraint")
    protected List<NOSConstraintType> constraint;
    @XmlElement(name = "Issue")
    protected List<NOSIssueType> issue;
    @XmlElement(name = "Note")
    protected List<NOSAssessmentNoteType> note;
    @XmlElement(name = "Limit")
    protected List<NOSRiemnsLimitType> limit;
    @XmlAttribute(name = "operationType")
    protected NOSOperationType operationType;

    /**
     * Gets the value of the sheetId property.
     * 
     */
    public int getSheetId() {
        return sheetId;
    }

    /**
     * Sets the value of the sheetId property.
     * 
     */
    public void setSheetId(int value) {
        this.sheetId = value;
    }

    /**
     * Gets the value of the assessmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAssessmentDate() {
        return assessmentDate;
    }

    /**
     * Sets the value of the assessmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAssessmentDate(XMLGregorianCalendar value) {
        this.assessmentDate = value;
    }

    /**
     * Gets the value of the assessmentTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssessmentTitle() {
        return assessmentTitle;
    }

    /**
     * Sets the value of the assessmentTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssessmentTitle(String value) {
        this.assessmentTitle = value;
    }

    /**
     * Gets the value of the requiresReview property.
     * 
     */
    public boolean isRequiresReview() {
        return requiresReview;
    }

    /**
     * Sets the value of the requiresReview property.
     * 
     */
    public void setRequiresReview(boolean value) {
        this.requiresReview = value;
    }

    /**
     * Gets the value of the outage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NOSAssessmentType.Outage }
     * 
     * 
     */
    public List<NOSAssessmentType.Outage> getOutage() {
        if (outage == null) {
            outage = new ArrayList<NOSAssessmentType.Outage>();
        }
        return this.outage;
    }

    /**
     * Gets the value of the constraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NOSConstraintType }
     * 
     * 
     */
    public List<NOSConstraintType> getConstraint() {
        if (constraint == null) {
            constraint = new ArrayList<NOSConstraintType>();
        }
        return this.constraint;
    }

    /**
     * Gets the value of the issue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NOSIssueType }
     * 
     * 
     */
    public List<NOSIssueType> getIssue() {
        if (issue == null) {
            issue = new ArrayList<NOSIssueType>();
        }
        return this.issue;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NOSAssessmentNoteType }
     * 
     * 
     */
    public List<NOSAssessmentNoteType> getNote() {
        if (note == null) {
            note = new ArrayList<NOSAssessmentNoteType>();
        }
        return this.note;
    }

    /**
     * Gets the value of the limit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the limit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLimit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NOSRiemnsLimitType }
     * 
     * 
     */
    public List<NOSRiemnsLimitType> getLimit() {
        if (limit == null) {
            limit = new ArrayList<NOSRiemnsLimitType>();
        }
        return this.limit;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link NOSOperationType }
     *     
     */
    public NOSOperationType getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NOSOperationType }
     *     
     */
    public void setOperationType(NOSOperationType value) {
        this.operationType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CompanyBookingId" type="{urn:aseXML:r38}CompanyBookingIdType"/>
     *         &lt;element name="CompanyOutageId" type="{urn:aseXML:r38}CompanyOutageIdType"/>
     *         &lt;element name="TNSPId" type="{urn:aseXML:r38}PartyIdentifier" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="operationType" type="{urn:aseXML:r38}NOSOperationType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "companyBookingId",
        "companyOutageId",
        "tnspId"
    })
    public static class Outage {

        @XmlElement(name = "CompanyBookingId", required = true)
        protected String companyBookingId;
        @XmlElement(name = "CompanyOutageId", required = true)
        protected String companyOutageId;
        @XmlElement(name = "TNSPId")
        protected PartyIdentifier tnspId;
        @XmlAttribute(name = "operationType")
        protected NOSOperationType operationType;

        /**
         * Gets the value of the companyBookingId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyBookingId() {
            return companyBookingId;
        }

        /**
         * Sets the value of the companyBookingId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyBookingId(String value) {
            this.companyBookingId = value;
        }

        /**
         * Gets the value of the companyOutageId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyOutageId() {
            return companyOutageId;
        }

        /**
         * Sets the value of the companyOutageId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyOutageId(String value) {
            this.companyOutageId = value;
        }

        /**
         * Gets the value of the tnspId property.
         * 
         * @return
         *     possible object is
         *     {@link PartyIdentifier }
         *     
         */
        public PartyIdentifier getTNSPId() {
            return tnspId;
        }

        /**
         * Sets the value of the tnspId property.
         * 
         * @param value
         *     allowed object is
         *     {@link PartyIdentifier }
         *     
         */
        public void setTNSPId(PartyIdentifier value) {
            this.tnspId = value;
        }

        /**
         * Gets the value of the operationType property.
         * 
         * @return
         *     possible object is
         *     {@link NOSOperationType }
         *     
         */
        public NOSOperationType getOperationType() {
            return operationType;
        }

        /**
         * Sets the value of the operationType property.
         * 
         * @param value
         *     allowed object is
         *     {@link NOSOperationType }
         *     
         */
        public void setOperationType(NOSOperationType value) {
            this.operationType = value;
        }

    }

}
