//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This transaction contains NOS information that may be a response to an information request transaction or generated by NEMMCO on the change of an assessment.
 * 
 * <p>Java class for NOSInfoResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NOSInfoResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Booking" type="{urn:aseXML:r38}BookingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OutageStatus" type="{urn:aseXML:r38}OutageStatusType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OutageConstraint" type="{urn:aseXML:r38}OutageConstraintType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Assessment" type="{urn:aseXML:r38}NOSAssessmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NOSEquipment" type="{urn:aseXML:r38}EquipmentBaseType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{urn:aseXML:r38}r38" default="r38" />
 *       &lt;attribute name="InfoType" use="required" type="{urn:aseXML:r38}NOSInfoType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NOSInfoResponse", propOrder = {
    "booking",
    "outageStatus",
    "outageConstraint",
    "assessment",
    "nosEquipment"
})
public class NOSInfoResponse {

    @XmlElement(name = "Booking")
    protected List<BookingType> booking;
    @XmlElement(name = "OutageStatus")
    protected List<OutageStatusType> outageStatus;
    @XmlElement(name = "OutageConstraint")
    protected List<OutageConstraintType> outageConstraint;
    @XmlElement(name = "Assessment")
    protected List<NOSAssessmentType> assessment;
    @XmlElement(name = "NOSEquipment")
    protected List<EquipmentBaseType> nosEquipment;
    @XmlAttribute(name = "version")
    protected R38 version;
    @XmlAttribute(name = "InfoType", required = true)
    protected NOSInfoType infoType;

    /**
     * Gets the value of the booking property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the booking property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBooking().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BookingType }
     * 
     * 
     */
    public List<BookingType> getBooking() {
        if (booking == null) {
            booking = new ArrayList<BookingType>();
        }
        return this.booking;
    }

    /**
     * Gets the value of the outageStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outageStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutageStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutageStatusType }
     * 
     * 
     */
    public List<OutageStatusType> getOutageStatus() {
        if (outageStatus == null) {
            outageStatus = new ArrayList<OutageStatusType>();
        }
        return this.outageStatus;
    }

    /**
     * Gets the value of the outageConstraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outageConstraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutageConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutageConstraintType }
     * 
     * 
     */
    public List<OutageConstraintType> getOutageConstraint() {
        if (outageConstraint == null) {
            outageConstraint = new ArrayList<OutageConstraintType>();
        }
        return this.outageConstraint;
    }

    /**
     * Gets the value of the assessment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assessment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssessment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NOSAssessmentType }
     * 
     * 
     */
    public List<NOSAssessmentType> getAssessment() {
        if (assessment == null) {
            assessment = new ArrayList<NOSAssessmentType>();
        }
        return this.assessment;
    }

    /**
     * Gets the value of the nosEquipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nosEquipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNOSEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentBaseType }
     * 
     * 
     */
    public List<EquipmentBaseType> getNOSEquipment() {
        if (nosEquipment == null) {
            nosEquipment = new ArrayList<EquipmentBaseType>();
        }
        return this.nosEquipment;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R38 }
     *     
     */
    public R38 getVersion() {
        if (version == null) {
            return R38 .R_38;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R38 }
     *     
     */
    public void setVersion(R38 value) {
        this.version = value;
    }

    /**
     * Gets the value of the infoType property.
     * 
     * @return
     *     possible object is
     *     {@link NOSInfoType }
     *     
     */
    public NOSInfoType getInfoType() {
        return infoType;
    }

    /**
     * Sets the value of the infoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NOSInfoType }
     *     
     */
    public void setInfoType(NOSInfoType value) {
        this.infoType = value;
    }

}
