//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Two winding Transformer
 * 
 * <p>Java class for NOSTwoWindingTransformerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NOSTwoWindingTransformerType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:aseXML:r38}NOSEquipmentType">
 *       &lt;sequence>
 *         &lt;element name="Voltage2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{urn:aseXML:r38}NOSVoltage">
 *               &lt;minInclusive value="0.2"/>
 *               &lt;maxInclusive value="400.0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NOSTwoWindingTransformerType", propOrder = {
    "voltage2"
})
@XmlSeeAlso({
    NOSThreeWindingTransformerType.class
})
public class NOSTwoWindingTransformerType
    extends NOSEquipmentType
{

    @XmlElement(name = "Voltage2")
    protected BigDecimal voltage2;

    /**
     * Gets the value of the voltage2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVoltage2() {
        return voltage2;
    }

    /**
     * Sets the value of the voltage2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVoltage2(BigDecimal value) {
        this.voltage2 = value;
    }

}
