//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for r11_p1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="r11_p1">
 *   &lt;restriction base="{urn:aseXML:r38}ReleaseIdentifier">
 *     &lt;enumeration value="r11_p1"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "r11_p1")
@XmlEnum
public enum R11P1 {

    @XmlEnumValue("r11_p1")
    R_11_P_1("r11_p1");
    private final String value;

    R11P1(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static R11P1 fromValue(String v) {
        for (R11P1 c: R11P1 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
