//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Purpose - Define the structure of removed equipment.
 * 
 * <p>Java class for RemovedMeteringEquipment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemovedMeteringEquipment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RemovedEquipmentType" type="{urn:aseXML:r38}MeterEquipmentType"/>
 *         &lt;element name="MeteringEquipment" type="{urn:aseXML:r38}NMIStandingData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemovedMeteringEquipment", propOrder = {
    "removedEquipmentType",
    "meteringEquipment"
})
public class RemovedMeteringEquipment {

    @XmlElement(name = "RemovedEquipmentType", required = true)
    @XmlSchemaType(name = "string")
    protected MeterEquipmentType removedEquipmentType;
    @XmlElement(name = "MeteringEquipment", required = true)
    protected NMIStandingData meteringEquipment;

    /**
     * Gets the value of the removedEquipmentType property.
     * 
     * @return
     *     possible object is
     *     {@link MeterEquipmentType }
     *     
     */
    public MeterEquipmentType getRemovedEquipmentType() {
        return removedEquipmentType;
    }

    /**
     * Sets the value of the removedEquipmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeterEquipmentType }
     *     
     */
    public void setRemovedEquipmentType(MeterEquipmentType value) {
        this.removedEquipmentType = value;
    }

    /**
     * Gets the value of the meteringEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link NMIStandingData }
     *     
     */
    public NMIStandingData getMeteringEquipment() {
        return meteringEquipment;
    }

    /**
     * Sets the value of the meteringEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link NMIStandingData }
     *     
     */
    public void setMeteringEquipment(NMIStandingData value) {
        this.meteringEquipment = value;
    }

}
