//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestReason.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RequestReason">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Returned Mail"/>
 *     &lt;enumeration value="Missing Customer Details"/>
 *     &lt;enumeration value="Confirm Life Support"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Transfer Complete, no CDN Received"/>
 *     &lt;enumeration value="New Connection, no CDN Received"/>
 *     &lt;enumeration value="No response to rejected CDN"/>
 *     &lt;enumeration value="Data Quality Issue"/>
 *     &lt;enumeration value="Rec - confirm no SensitiveLoad"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RequestReason")
@XmlEnum
public enum RequestReason {

    @XmlEnumValue("Returned Mail")
    RETURNED_MAIL("Returned Mail"),
    @XmlEnumValue("Missing Customer Details")
    MISSING_CUSTOMER_DETAILS("Missing Customer Details"),
    @XmlEnumValue("Confirm Life Support")
    CONFIRM_LIFE_SUPPORT("Confirm Life Support"),
    @XmlEnumValue("Other")
    OTHER("Other"),
    @XmlEnumValue("Transfer Complete, no CDN Received")
    TRANSFER_COMPLETE_NO_CDN_RECEIVED("Transfer Complete, no CDN Received"),
    @XmlEnumValue("New Connection, no CDN Received")
    NEW_CONNECTION_NO_CDN_RECEIVED("New Connection, no CDN Received"),
    @XmlEnumValue("No response to rejected CDN")
    NO_RESPONSE_TO_REJECTED_CDN("No response to rejected CDN"),
    @XmlEnumValue("Data Quality Issue")
    DATA_QUALITY_ISSUE("Data Quality Issue"),
    @XmlEnumValue("Rec - confirm no SensitiveLoad")
    REC_CONFIRM_NO_SENSITIVE_LOAD("Rec - confirm no SensitiveLoad");
    private final String value;

    RequestReason(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RequestReason fromValue(String v) {
        for (RequestReason c: RequestReason.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
