//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceTimeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceTimeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="40"/>
 *     &lt;enumeration value="Any Time"/>
 *     &lt;enumeration value="Business Hours"/>
 *     &lt;enumeration value="Non-Business Hours"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ServiceTimeType")
@XmlEnum
public enum ServiceTimeType {

    @XmlEnumValue("Any Time")
    ANY_TIME("Any Time"),
    @XmlEnumValue("Business Hours")
    BUSINESS_HOURS("Business Hours"),
    @XmlEnumValue("Non-Business Hours")
    NON_BUSINESS_HOURS("Non-Business Hours");
    private final String value;

    ServiceTimeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceTimeType fromValue(String v) {
        for (ServiceTimeType c: ServiceTimeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
