//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Schema - Gas
 * 
 * <p>Java class for ServiceOrderGasNoAccessData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceOrderGasNoAccessData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="SpecialReadNoAccess" type="{urn:aseXML:r38}GasSpecialReadNoAccess"/>
 *         &lt;element name="DateOfAttemptedAccess" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceOrderGasNoAccessData", propOrder = {
    "specialReadNoAccess",
    "dateOfAttemptedAccess"
})
public class ServiceOrderGasNoAccessData {

    @XmlElement(name = "SpecialReadNoAccess")
    protected GasSpecialReadNoAccess specialReadNoAccess;
    @XmlElement(name = "DateOfAttemptedAccess")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfAttemptedAccess;

    /**
     * Gets the value of the specialReadNoAccess property.
     * 
     * @return
     *     possible object is
     *     {@link GasSpecialReadNoAccess }
     *     
     */
    public GasSpecialReadNoAccess getSpecialReadNoAccess() {
        return specialReadNoAccess;
    }

    /**
     * Sets the value of the specialReadNoAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasSpecialReadNoAccess }
     *     
     */
    public void setSpecialReadNoAccess(GasSpecialReadNoAccess value) {
        this.specialReadNoAccess = value;
    }

    /**
     * Gets the value of the dateOfAttemptedAccess property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfAttemptedAccess() {
        return dateOfAttemptedAccess;
    }

    /**
     * Sets the value of the dateOfAttemptedAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfAttemptedAccess(XMLGregorianCalendar value) {
        this.dateOfAttemptedAccess = value;
    }

}
