//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * Schema - Gas
 * 
 * <p>Java class for ServiceOrderMultiMeterData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceOrderMultiMeterData">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:aseXML:r38}BaseServiceOrderGasMeterData">
 *       &lt;sequence maxOccurs="999">
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="New" type="{urn:aseXML:r38}GasMultiMeterStandingDataType" minOccurs="0"/>
 *             &lt;element name="Removed" type="{urn:aseXML:r38}GasMultiMeterStandingDataType" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element name="Current" type="{urn:aseXML:r38}GasMultiMeterStandingDataType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceOrderMultiMeterData", propOrder = {
    "newAndRemovedOrCurrent"
})
public class ServiceOrderMultiMeterData
    extends BaseServiceOrderGasMeterData
{

    @XmlElementRefs({
        @XmlElementRef(name = "Removed", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Current", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "New", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<GasMultiMeterStandingDataType>> newAndRemovedOrCurrent;

    /**
     * Gets the value of the newAndRemovedOrCurrent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the newAndRemovedOrCurrent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNewAndRemovedOrCurrent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link GasMultiMeterStandingDataType }{@code >}
     * {@link JAXBElement }{@code <}{@link GasMultiMeterStandingDataType }{@code >}
     * {@link JAXBElement }{@code <}{@link GasMultiMeterStandingDataType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<GasMultiMeterStandingDataType>> getNewAndRemovedOrCurrent() {
        if (newAndRemovedOrCurrent == null) {
            newAndRemovedOrCurrent = new ArrayList<JAXBElement<GasMultiMeterStandingDataType>>();
        }
        return this.newAndRemovedOrCurrent;
    }

}
