//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Schema - Gas
 * 
 * <p>Java class for ServiceOrderGasCompletionData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceOrderGasCompletionData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateServiceOrderCompleted" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="TimeServiceOrderCompleted" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="MeterData" type="{urn:aseXML:r38}BaseServiceOrderGasMeterData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceOrderGasCompletionData", propOrder = {
    "dateServiceOrderCompleted",
    "timeServiceOrderCompleted",
    "meterData"
})
public class ServiceOrderGasCompletionData {

    @XmlElement(name = "DateServiceOrderCompleted", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateServiceOrderCompleted;
    @XmlElement(name = "TimeServiceOrderCompleted")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar timeServiceOrderCompleted;
    @XmlElement(name = "MeterData")
    protected BaseServiceOrderGasMeterData meterData;

    /**
     * Gets the value of the dateServiceOrderCompleted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateServiceOrderCompleted() {
        return dateServiceOrderCompleted;
    }

    /**
     * Sets the value of the dateServiceOrderCompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateServiceOrderCompleted(XMLGregorianCalendar value) {
        this.dateServiceOrderCompleted = value;
    }

    /**
     * Gets the value of the timeServiceOrderCompleted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeServiceOrderCompleted() {
        return timeServiceOrderCompleted;
    }

    /**
     * Sets the value of the timeServiceOrderCompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeServiceOrderCompleted(XMLGregorianCalendar value) {
        this.timeServiceOrderCompleted = value;
    }

    /**
     * Gets the value of the meterData property.
     * 
     * @return
     *     possible object is
     *     {@link BaseServiceOrderGasMeterData }
     *     
     */
    public BaseServiceOrderGasMeterData getMeterData() {
        return meterData;
    }

    /**
     * Sets the value of the meterData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseServiceOrderGasMeterData }
     *     
     */
    public void setMeterData(BaseServiceOrderGasMeterData value) {
        this.meterData = value;
    }

}
