//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Application - Meter Data Management
 * TransactionExchange - Settlement Data Delivery
 * TransactionGroup - MDMT
 * Priority - Low
 * Purpose - Provide settlement data
 * Detail - Only one type of settlement data can be delivered within a given transaction. 
 * 			
 * 
 * <p>Java class for SettlementDataNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SettlementDataNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="CSVAggregatedSettlementData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CSVNonAggregatedSettlementData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" type="{urn:aseXML:r38}r4" default="r4" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SettlementDataNotification", propOrder = {
    "csvAggregatedSettlementData",
    "csvNonAggregatedSettlementData"
})
public class SettlementDataNotification {

    @XmlElement(name = "CSVAggregatedSettlementData")
    protected String csvAggregatedSettlementData;
    @XmlElement(name = "CSVNonAggregatedSettlementData")
    protected String csvNonAggregatedSettlementData;
    @XmlAttribute(name = "version")
    protected R4 version;

    /**
     * Gets the value of the csvAggregatedSettlementData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSVAggregatedSettlementData() {
        return csvAggregatedSettlementData;
    }

    /**
     * Sets the value of the csvAggregatedSettlementData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSVAggregatedSettlementData(String value) {
        this.csvAggregatedSettlementData = value;
    }

    /**
     * Gets the value of the csvNonAggregatedSettlementData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSVNonAggregatedSettlementData() {
        return csvNonAggregatedSettlementData;
    }

    /**
     * Sets the value of the csvNonAggregatedSettlementData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSVNonAggregatedSettlementData(String value) {
        this.csvNonAggregatedSettlementData = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link R4 }
     *     
     */
    public R4 getVersion() {
        if (version == null) {
            return R4 .R_4;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link R4 }
     *     
     */
    public void setVersion(R4 value) {
        this.version = value;
    }

}
