//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:36:34 AM AEDT 
//


package hamy.mdgen.api.generator.format.aseXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Schema - RemoteService.  User definitions block
 * 
 * <p>Java class for UserDefData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserDefData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserDef1" type="{urn:aseXML:r38}UserDefinition" minOccurs="0"/>
 *         &lt;element name="UserDef2" type="{urn:aseXML:r38}UserDefinition" minOccurs="0"/>
 *         &lt;element name="UserDef3" type="{urn:aseXML:r38}UserDefinition" minOccurs="0"/>
 *         &lt;element name="UserDef4" type="{urn:aseXML:r38}UserDefinition" minOccurs="0"/>
 *         &lt;element name="UserDef5" type="{urn:aseXML:r38}UserDefinition" minOccurs="0"/>
 *         &lt;element name="UserDef6" type="{urn:aseXML:r38}UserDefinition" minOccurs="0"/>
 *         &lt;element name="UserDef7" type="{urn:aseXML:r38}UserDefinition" minOccurs="0"/>
 *         &lt;element name="UserDef8" type="{urn:aseXML:r38}UserDefinition" minOccurs="0"/>
 *         &lt;element name="UserDef9" type="{urn:aseXML:r38}UserDefinition" minOccurs="0"/>
 *         &lt;element name="UserDef10" type="{urn:aseXML:r38}UserDefinition" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserDefData", propOrder = {
    "userDef1",
    "userDef2",
    "userDef3",
    "userDef4",
    "userDef5",
    "userDef6",
    "userDef7",
    "userDef8",
    "userDef9",
    "userDef10"
})
public class UserDefData {

    @XmlElement(name = "UserDef1")
    protected String userDef1;
    @XmlElement(name = "UserDef2")
    protected String userDef2;
    @XmlElement(name = "UserDef3")
    protected String userDef3;
    @XmlElement(name = "UserDef4")
    protected String userDef4;
    @XmlElement(name = "UserDef5")
    protected String userDef5;
    @XmlElement(name = "UserDef6")
    protected String userDef6;
    @XmlElement(name = "UserDef7")
    protected String userDef7;
    @XmlElement(name = "UserDef8")
    protected String userDef8;
    @XmlElement(name = "UserDef9")
    protected String userDef9;
    @XmlElement(name = "UserDef10")
    protected String userDef10;

    /**
     * Gets the value of the userDef1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef1() {
        return userDef1;
    }

    /**
     * Sets the value of the userDef1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef1(String value) {
        this.userDef1 = value;
    }

    /**
     * Gets the value of the userDef2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef2() {
        return userDef2;
    }

    /**
     * Sets the value of the userDef2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef2(String value) {
        this.userDef2 = value;
    }

    /**
     * Gets the value of the userDef3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef3() {
        return userDef3;
    }

    /**
     * Sets the value of the userDef3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef3(String value) {
        this.userDef3 = value;
    }

    /**
     * Gets the value of the userDef4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef4() {
        return userDef4;
    }

    /**
     * Sets the value of the userDef4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef4(String value) {
        this.userDef4 = value;
    }

    /**
     * Gets the value of the userDef5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef5() {
        return userDef5;
    }

    /**
     * Sets the value of the userDef5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef5(String value) {
        this.userDef5 = value;
    }

    /**
     * Gets the value of the userDef6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef6() {
        return userDef6;
    }

    /**
     * Sets the value of the userDef6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef6(String value) {
        this.userDef6 = value;
    }

    /**
     * Gets the value of the userDef7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef7() {
        return userDef7;
    }

    /**
     * Sets the value of the userDef7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef7(String value) {
        this.userDef7 = value;
    }

    /**
     * Gets the value of the userDef8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef8() {
        return userDef8;
    }

    /**
     * Sets the value of the userDef8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef8(String value) {
        this.userDef8 = value;
    }

    /**
     * Gets the value of the userDef9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef9() {
        return userDef9;
    }

    /**
     * Sets the value of the userDef9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef9(String value) {
        this.userDef9 = value;
    }

    /**
     * Gets the value of the userDef10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDef10() {
        return userDef10;
    }

    /**
     * Sets the value of the userDef10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDef10(String value) {
        this.userDef10 = value;
    }

}
