//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.27 at 10:17:06 AM AEDT 
//


package hamy.mdgen.api.generator.format.xai.CMIMDSeeder;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hamy.mdgen.api.backend.xai.CMIMDSeeder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CMIMDSeederFromDateTime_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "fromDateTime");
    private final static QName _CMIMDSeederIsReprocessPerformed_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "isReprocessPerformed");
    private final static QName _CMIMDSeederRetryUntilDateTime_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "retryUntilDateTime");
    private final static QName _CMIMDSeederToDateTime_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "toDateTime");
    private final static QName _CMIMDSeederCreationDateTime_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "creationDateTime");
    private final static QName _CMIMDSeederExecutionMethod_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "executionMethod");
    private final static QName _CMIMDSeederVeeGroupRole_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "veeGroupRole");
    private final static QName _CMIMDSeederDataSource_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "dataSource");
    private final static QName _CMIMDSeederStartReadingDateTime_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "startReadingDateTime");
    private final static QName _CMIMDSeederNextRetryDateTime_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "nextRetryDateTime");
    private final static QName _CMIMDSeederStartReadingCondition_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "startReadingCondition");
    private final static QName _CMIMDSeederIsAutomatedRetry_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "isAutomatedRetry");
    private final static QName _CMIMDSeederIsTraceOn_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "isTraceOn");
    private final static QName _CMIMDSeederBoStatusDateTime_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "boStatusDateTime");
    private final static QName _CMIMDSeederProcessDataLogsLogsListLogsEntryLogDateTime_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "logDateTime");
    private final static QName _CMIMDSeederProcessDataLogsLogsListLogsEntryLogEntryType_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "logEntryType");
    private final static QName _CMIMDSeederPreVEESoCodeGroupSoCodeListSoCode_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "soCode");
    private final static QName _CMIMDSeederPreVEEMsrsMLDt_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "dt");
    private final static QName _CMIMDSeederPreVEEMsrsMLUe_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "ue");
    private final static QName _CMIMDSeederPreVEEMsrsMLRc_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "rc");
    private final static QName _CMIMDSeederPreVEEMsrsMLFc_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "fc");
    private final static QName _CMIMDSeederPreVEEMcIS_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "mcIS");
    private final static QName _CMIMDSeederPreVEEEnDt_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "enDt");
    private final static QName _CMIMDSeederPreVEENem12UpdateDateTime_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "nem12UpdateDateTime");
    private final static QName _CMIMDSeederPreVEEStDt_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "stDt");
    private final static QName _CMIMDSeederPreVEECcond_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "ccond");
    private final static QName _CMIMDSeederPreVEEInShift_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "inShift");
    private final static QName _CMIMDSeederPreVEEImdType_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "imdType");
    private final static QName _CMIMDSeederPreVEESpi_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "spi");
    private final static QName _CMIMDSeederProcessDataIsShiftedStartEnd_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "isShiftedStartEnd");
    private final static QName _CMIMDSeederProcessDataIsErrorEncountered_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "isErrorEncountered");
    private final static QName _CMIMDSeederProcessDataDisableSubtractiveConsumptionCalculation_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "disableSubtractiveConsumptionCalculation");
    private final static QName _CMIMDSeederProcessDataImdImportDateTimeFormat_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "imdImportDateTimeFormat");
    private final static QName _CMIMDSeederProcessDataIsTimeZoneConverted_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "isTimeZoneConverted");
    private final static QName _CMIMDSeederProcessDataIsShiftedIntervals_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "isShiftedIntervals");
    private final static QName _CMIMDSeederProcessDataIsShiftCorrectedIntervals_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "isShiftCorrectedIntervals");
    private final static QName _CMIMDSeederProcessDataIntervalScalarIndicator_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "intervalScalarIndicator");
    private final static QName _CMIMDSeederProcessDataAllowNonZeroIntervalsForEstimate_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "allowNonZeroIntervalsForEstimate");
    private final static QName _CMIMDSeederProcessDataIsEndDateTimeDerived_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "isEndDateTimeDerived");
    private final static QName _CMIMDSeederProcessDataMultiplierApplied_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "multiplierApplied");
    private final static QName _CMIMDSeederProcessDataIsShiftCorrectedStartEnd_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "isShiftCorrectedStartEnd");
    private final static QName _CMIMDSeederProcessDataDisableReEstimate_QNAME = new QName("http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", "disableReEstimate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hamy.mdgen.api.backend.xai.CMIMDSeeder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CMIMDSeeder }
     * 
     */
    public CMIMDSeeder createCMIMDSeeder() {
        return new CMIMDSeeder();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.ProcessData }
     * 
     */
    public CMIMDSeeder.ProcessData createCMIMDSeederProcessData() {
        return new CMIMDSeeder.ProcessData();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.ProcessData.DeviceEventTypes }
     * 
     */
    public CMIMDSeeder.ProcessData.DeviceEventTypes createCMIMDSeederProcessDataDeviceEventTypes() {
        return new CMIMDSeeder.ProcessData.DeviceEventTypes();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.ProcessData.Logs }
     * 
     */
    public CMIMDSeeder.ProcessData.Logs createCMIMDSeederProcessDataLogs() {
        return new CMIMDSeeder.ProcessData.Logs();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.ProcessData.Logs.LogsList }
     * 
     */
    public CMIMDSeeder.ProcessData.Logs.LogsList createCMIMDSeederProcessDataLogsLogsList() {
        return new CMIMDSeeder.ProcessData.Logs.LogsList();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.PreVEE }
     * 
     */
    public CMIMDSeeder.PreVEE createCMIMDSeederPreVEE() {
        return new CMIMDSeeder.PreVEE();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.PreVEE.SoCodeGroup }
     * 
     */
    public CMIMDSeeder.PreVEE.SoCodeGroup createCMIMDSeederPreVEESoCodeGroup() {
        return new CMIMDSeeder.PreVEE.SoCodeGroup();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.PreVEE.Msrs }
     * 
     */
    public CMIMDSeeder.PreVEE.Msrs createCMIMDSeederPreVEEMsrs() {
        return new CMIMDSeeder.PreVEE.Msrs();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.PreVEE.Msrs.ML }
     * 
     */
    public CMIMDSeeder.PreVEE.Msrs.ML createCMIMDSeederPreVEEMsrsML() {
        return new CMIMDSeeder.PreVEE.Msrs.ML();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.PreVEE.Msrs.ML.Sts }
     * 
     */
    public CMIMDSeeder.PreVEE.Msrs.ML.Sts createCMIMDSeederPreVEEMsrsMLSts() {
        return new CMIMDSeeder.PreVEE.Msrs.ML.Sts();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.PreVEE.Sts }
     * 
     */
    public CMIMDSeeder.PreVEE.Sts createCMIMDSeederPreVEESts() {
        return new CMIMDSeeder.PreVEE.Sts();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.SyncIMDOtherInfo }
     * 
     */
    public CMIMDSeeder.SyncIMDOtherInfo createCMIMDSeederSyncIMDOtherInfo() {
        return new CMIMDSeeder.SyncIMDOtherInfo();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.ProcessData.DeviceEventTypes.DeviceEventTypesList }
     * 
     */
    public CMIMDSeeder.ProcessData.DeviceEventTypes.DeviceEventTypesList createCMIMDSeederProcessDataDeviceEventTypesDeviceEventTypesList() {
        return new CMIMDSeeder.ProcessData.DeviceEventTypes.DeviceEventTypesList();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.ProcessData.Logs.LogsList.LogsEntry }
     * 
     */
    public CMIMDSeeder.ProcessData.Logs.LogsList.LogsEntry createCMIMDSeederProcessDataLogsLogsListLogsEntry() {
        return new CMIMDSeeder.ProcessData.Logs.LogsList.LogsEntry();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.PreVEE.SoCodeGroup.SoCodeList }
     * 
     */
    public CMIMDSeeder.PreVEE.SoCodeGroup.SoCodeList createCMIMDSeederPreVEESoCodeGroupSoCodeList() {
        return new CMIMDSeeder.PreVEE.SoCodeGroup.SoCodeList();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.PreVEE.Msrs.ML.Sts.StsL }
     * 
     */
    public CMIMDSeeder.PreVEE.Msrs.ML.Sts.StsL createCMIMDSeederPreVEEMsrsMLStsStsL() {
        return new CMIMDSeeder.PreVEE.Msrs.ML.Sts.StsL();
    }

    /**
     * Create an instance of {@link CMIMDSeeder.PreVEE.Sts.StsL }
     * 
     */
    public CMIMDSeeder.PreVEE.Sts.StsL createCMIMDSeederPreVEEStsStsL() {
        return new CMIMDSeeder.PreVEE.Sts.StsL();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "fromDateTime", scope = CMIMDSeeder.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederFromDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederFromDateTime_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "isReprocessPerformed", scope = CMIMDSeeder.class)
    public JAXBElement<String> createCMIMDSeederIsReprocessPerformed(String value) {
        return new JAXBElement<String>(_CMIMDSeederIsReprocessPerformed_QNAME, String.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "retryUntilDateTime", scope = CMIMDSeeder.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederRetryUntilDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederRetryUntilDateTime_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "toDateTime", scope = CMIMDSeeder.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederToDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederToDateTime_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "creationDateTime", scope = CMIMDSeeder.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederCreationDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederCreationDateTime_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "executionMethod", scope = CMIMDSeeder.class)
    public JAXBElement<String> createCMIMDSeederExecutionMethod(String value) {
        return new JAXBElement<String>(_CMIMDSeederExecutionMethod_QNAME, String.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "veeGroupRole", scope = CMIMDSeeder.class)
    public JAXBElement<String> createCMIMDSeederVeeGroupRole(String value) {
        return new JAXBElement<String>(_CMIMDSeederVeeGroupRole_QNAME, String.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "dataSource", scope = CMIMDSeeder.class)
    public JAXBElement<String> createCMIMDSeederDataSource(String value) {
        return new JAXBElement<String>(_CMIMDSeederDataSource_QNAME, String.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "startReadingDateTime", scope = CMIMDSeeder.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederStartReadingDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederStartReadingDateTime_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "nextRetryDateTime", scope = CMIMDSeeder.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederNextRetryDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederNextRetryDateTime_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "startReadingCondition", scope = CMIMDSeeder.class)
    public JAXBElement<String> createCMIMDSeederStartReadingCondition(String value) {
        return new JAXBElement<String>(_CMIMDSeederStartReadingCondition_QNAME, String.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "isAutomatedRetry", scope = CMIMDSeeder.class)
    public JAXBElement<String> createCMIMDSeederIsAutomatedRetry(String value) {
        return new JAXBElement<String>(_CMIMDSeederIsAutomatedRetry_QNAME, String.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "isTraceOn", scope = CMIMDSeeder.class)
    public JAXBElement<String> createCMIMDSeederIsTraceOn(String value) {
        return new JAXBElement<String>(_CMIMDSeederIsTraceOn_QNAME, String.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "boStatusDateTime", scope = CMIMDSeeder.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederBoStatusDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederBoStatusDateTime_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "logDateTime", scope = CMIMDSeeder.ProcessData.Logs.LogsList.LogsEntry.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederProcessDataLogsLogsListLogsEntryLogDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederProcessDataLogsLogsListLogsEntryLogDateTime_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.ProcessData.Logs.LogsList.LogsEntry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "logEntryType", scope = CMIMDSeeder.ProcessData.Logs.LogsList.LogsEntry.class)
    public JAXBElement<String> createCMIMDSeederProcessDataLogsLogsListLogsEntryLogEntryType(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataLogsLogsListLogsEntryLogEntryType_QNAME, String.class, CMIMDSeeder.ProcessData.Logs.LogsList.LogsEntry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "soCode", scope = CMIMDSeeder.PreVEE.SoCodeGroup.SoCodeList.class)
    public JAXBElement<String> createCMIMDSeederPreVEESoCodeGroupSoCodeListSoCode(String value) {
        return new JAXBElement<String>(_CMIMDSeederPreVEESoCodeGroupSoCodeListSoCode_QNAME, String.class, CMIMDSeeder.PreVEE.SoCodeGroup.SoCodeList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "dt", scope = CMIMDSeeder.PreVEE.Msrs.ML.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederPreVEEMsrsMLDt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederPreVEEMsrsMLDt_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.PreVEE.Msrs.ML.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "ue", scope = CMIMDSeeder.PreVEE.Msrs.ML.class)
    public JAXBElement<String> createCMIMDSeederPreVEEMsrsMLUe(String value) {
        return new JAXBElement<String>(_CMIMDSeederPreVEEMsrsMLUe_QNAME, String.class, CMIMDSeeder.PreVEE.Msrs.ML.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "rc", scope = CMIMDSeeder.PreVEE.Msrs.ML.class)
    public JAXBElement<String> createCMIMDSeederPreVEEMsrsMLRc(String value) {
        return new JAXBElement<String>(_CMIMDSeederPreVEEMsrsMLRc_QNAME, String.class, CMIMDSeeder.PreVEE.Msrs.ML.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "fc", scope = CMIMDSeeder.PreVEE.Msrs.ML.class)
    public JAXBElement<String> createCMIMDSeederPreVEEMsrsMLFc(String value) {
        return new JAXBElement<String>(_CMIMDSeederPreVEEMsrsMLFc_QNAME, String.class, CMIMDSeeder.PreVEE.Msrs.ML.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "mcIS", scope = CMIMDSeeder.PreVEE.class)
    public JAXBElement<String> createCMIMDSeederPreVEEMcIS(String value) {
        return new JAXBElement<String>(_CMIMDSeederPreVEEMcIS_QNAME, String.class, CMIMDSeeder.PreVEE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "enDt", scope = CMIMDSeeder.PreVEE.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederPreVEEEnDt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederPreVEEEnDt_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.PreVEE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "nem12UpdateDateTime", scope = CMIMDSeeder.PreVEE.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederPreVEENem12UpdateDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederPreVEENem12UpdateDateTime_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.PreVEE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "stDt", scope = CMIMDSeeder.PreVEE.class)
    public JAXBElement<XMLGregorianCalendar> createCMIMDSeederPreVEEStDt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CMIMDSeederPreVEEStDt_QNAME, XMLGregorianCalendar.class, CMIMDSeeder.PreVEE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "ccond", scope = CMIMDSeeder.PreVEE.class)
    public JAXBElement<String> createCMIMDSeederPreVEECcond(String value) {
        return new JAXBElement<String>(_CMIMDSeederPreVEECcond_QNAME, String.class, CMIMDSeeder.PreVEE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "inShift", scope = CMIMDSeeder.PreVEE.class)
    public JAXBElement<String> createCMIMDSeederPreVEEInShift(String value) {
        return new JAXBElement<String>(_CMIMDSeederPreVEEInShift_QNAME, String.class, CMIMDSeeder.PreVEE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "imdType", scope = CMIMDSeeder.PreVEE.class)
    public JAXBElement<String> createCMIMDSeederPreVEEImdType(String value) {
        return new JAXBElement<String>(_CMIMDSeederPreVEEImdType_QNAME, String.class, CMIMDSeeder.PreVEE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "spi", scope = CMIMDSeeder.PreVEE.class)
    public JAXBElement<Integer> createCMIMDSeederPreVEESpi(Integer value) {
        return new JAXBElement<Integer>(_CMIMDSeederPreVEESpi_QNAME, Integer.class, CMIMDSeeder.PreVEE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "isShiftedStartEnd", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataIsShiftedStartEnd(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataIsShiftedStartEnd_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "isErrorEncountered", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataIsErrorEncountered(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataIsErrorEncountered_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "disableSubtractiveConsumptionCalculation", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataDisableSubtractiveConsumptionCalculation(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataDisableSubtractiveConsumptionCalculation_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "imdImportDateTimeFormat", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataImdImportDateTimeFormat(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataImdImportDateTimeFormat_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "isTimeZoneConverted", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataIsTimeZoneConverted(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataIsTimeZoneConverted_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "isShiftedIntervals", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataIsShiftedIntervals(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataIsShiftedIntervals_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "isShiftCorrectedIntervals", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataIsShiftCorrectedIntervals(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataIsShiftCorrectedIntervals_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "intervalScalarIndicator", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataIntervalScalarIndicator(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataIntervalScalarIndicator_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "allowNonZeroIntervalsForEstimate", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataAllowNonZeroIntervalsForEstimate(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataAllowNonZeroIntervalsForEstimate_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "isEndDateTimeDerived", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataIsEndDateTimeDerived(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataIsEndDateTimeDerived_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "multiplierApplied", scope = CMIMDSeeder.ProcessData.class, defaultValue = "false")
    public JAXBElement<Boolean> createCMIMDSeederProcessDataMultiplierApplied(Boolean value) {
        return new JAXBElement<Boolean>(_CMIMDSeederProcessDataMultiplierApplied_QNAME, Boolean.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "isShiftCorrectedStartEnd", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataIsShiftCorrectedStartEnd(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataIsShiftCorrectedStartEnd_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ouaf.oracle.com/schemas/f1bo/CM-IMDSeeder", name = "disableReEstimate", scope = CMIMDSeeder.ProcessData.class)
    public JAXBElement<String> createCMIMDSeederProcessDataDisableReEstimate(String value) {
        return new JAXBElement<String>(_CMIMDSeederProcessDataDisableReEstimate_QNAME, String.class, CMIMDSeeder.ProcessData.class, value);
    }

}
